### PR TITLE
66 fix/replace wp get sites() with get sites()

### LINKED ISSUE #66: Replace wp_get_sites() with get_sites() in email-log/include/Core/DB/TableManager.php
- [ ] Replace `wp_get_sites()` with `get_sites()` in `email-log/include/Core/DB/TableManager.php`
- [ ] Test the above change and make sure it works
- [ ] Replace `wp_get_sites()` with `get_sites()` in `email-log/uninstall.php` in line number 16
- [ ] Test the above change and make sure it works

### PR DESCRIPTION
**Pull request by anandB000**
Fix #66

### CODE REVIEW

File: include/Core/DB/TableManager.php [hunk 1]
```diff
@@ -42,7 +42,7 @@ public function on_activate( $network_wide ) {
 			// Note: if there are more than 10,000 blogs or
 			// if `wp_is_large_network` filter is set, then this may fail.
 			// TODO: Take care of the deprecated function.
```
Comment (sudar) [inline include/Core/DB/TableManager.php]: Remove this comment, since you are handling the deprecated function in the commit.

File: include/Core/DB/TableManager.php [hunk 2]
```diff
@@ -39,10 +39,7 @@ public function load() {
 	 */
 	public function on_activate( $network_wide ) {
 		if ( is_multisite() && $network_wide ) {
-			// Note: if there are more than 10,000 blogs or
-			// if `wp_is_large_network` filter is set, then this may fail.
-			// TODO: Take care of the deprecated function.
-			$sites = wp_get_sites();
```
Comment (sudar) [inline include/Core/DB/TableManager.php]: You should remove only the comment about the deprecated function. The other comment still holds good.
